# We use strings for types so that pandas.astype() can read them easily
# and we use 'nullable' types (Capitalized) to prevent crashes on missing data.
# TODO - needs updating
STRAVA_COLUMN_TYPES = {
    "athlete_id": "Int64",
    "name": "string",
    "distance": "float64",
    "moving_time": "Int64",
    "elapsed_time": "Int64",
    "total_elevation_gain": "float64",
    "type": "category",
    "sport_type": "category",
    "workout_type": "float64",
    "device_name": "category",
    "id": "Int64",
    "start_date": "datetime64[ns]",
    "start_date_local": "datetime64[ns]",
    "timezone": "string",
    "utc_offset": "Int64",
    "location_city": "string",
    "location_state": "string",
    "location_country": "string",
    "achievement_count": "Int64",
    "kudos_count": "Int64",
    "comment_count": "Int64",
    "athlete_count": "Int64",
    "photo_count": "Int64",
    "summary_polyline": "string",
    "trainer": "bool",
    "commute": "bool",
    "manual": "bool",
    "private": "bool",
    "visibility": "category",
    "flagged": "bool",
    "gear_id": "string",
    "start_lat": "float64",
    "start_lng": "float64",
    "end_lat": "float64",
    "end_lng": "float64",
    "average_speed": "float64",
    "max_speed": "float64",
    "average_cadence": "float64",
    "has_heartrate": "bool",
    "average_heartrate": "float64",
    "max_heartrate": "Int64",
    "heartrate_opt_out": "bool",
    "display_hide_heartrate_option": "bool",
    "elev_high": "float64",
    "elev_low": "float64",
    "upload_id": "Int64",
    "upload_id_str": "string",
    "external_id": "string",
    "from_accepted_tag": "bool",
    "pr_count": "Int64",
    "total_photo_count": "Int64",
    "has_kudoed": "bool",
    "average_temp": "float64",
}
